### ISSUE TITLE
REQUEST: how to overcome the 500 results-limit? With Paging or searchcondition on ID?

### ISSUE THREAD

**Issue by AndyVanDePutte** [M-Files/Libraries.MFWSClient#1]
Hi,

I'm struggling with the 
    mfClient.ObjectSearchOperations.SearchForObjectsByConditions

The result limit is set to 500 (probably for performance).

Is there a way to do paging? For example, can I add a Searchcondition to the parameters based on the ObjVer.ID  (to do my own paging?). So I can do a search on ID > 1000 (for example) ?

Or is there another method available for this?

Thanks a lot
Andy Van De Putte
Build-Software

**Comment by CraigHawker** [comment]
Hi Andy,

The page size can be increased by following the guidance here: https://developer.m-files.com/APIs/REST-API/Searching/#increasing-the-number-of-results
If there is not already an optional parameter to allow this to be provided when executing a search then it would need to be added.  If you would like to do so and submit a pull request then I will look to merge it in and update the nuget package.

There isn't directly a way to do paging, unfortunately.  What you can do is something we refer to as a "segmented search" (https://github.com/M-Files/MFilesSamplesAndLibraries/tree/master/Samples/COM%20API/SegmentedSearch#readme), but it's far from ideal.  It works similarly to your ID suggestion ("get me all objects that match conditions A, B, and C, but that have IDs between 0 and 1000").  You then iterate through the next blocks ("get me all objects that match conditions A, B, and C, but that have IDs between 1000 and 2000") until there are no additional items that match the search.

_Note: The sample above is for the COM API.  This can be done in the REST API using an undocumented parameter for "i" for the object ID, I seem to recall.  There may be no class defined to allow you to provide this parameter so, again, feel free to look at how the search condition classes work in this library and submit a pull request._

Regards,

Craig.

**Comment by AndyVanDePutte** [comment]
Dear Mr. Hawker,
Hi Craig,

Thanks for your very fast response.
I changed the code and did a pull request…

In the code I added some optional parameters for the record-limit and added an overload to some method (for not breaking a lot of other tests).

  *   It was because we have to combine params (= conditions) with the optional parameter (for the limit).

I added a test as wel to test the limit.

I’m not sure if I did it right in github, because I’m used to use Azure Devops instead of github.

Thx a lot for helping us out!

A lot of greetings and best regards,
Andy

**Comment by CraigHawker** [comment]
Hi Andy,

Thank you for the [pull request](https://github.com/M-Files/Libraries.MFWSClient/pull/2) including both the implementation and tests.  After review, the changes are now available in release [1.0.4-alpha](https://www.nuget.org/packages/MFaaP.MFWSClient/1.0.4-alpha) which is publishing to nuget as I type this message.

I will close the issue now.  Thank you very much for both raising the question and also submitting the pull request.

Regards,

Craig.
