### ISSUE TITLE
Ability to update workflow State without checking out

### ISSUE THREAD

**Issue by shoebsd31** [M-Files/Libraries.MFWSClient#10]
Currently, in order to update the workflow state, I have to checkout the objectVersion, update the property and then check it in as follows : 

`var checkedOutObjVersion = client.ObjectOperations.CheckOut(updatedObjectVersion.ObjVer);
    client.ObjectPropertyOperations.SetProperty(DOCUMENT_OBJECT_TYPE_ID, checkedOutObjVersion.ObjVer.ID, workflowStatePropertyValue);
    var newObjectVersion = client.ObjectOperations.CheckIn(checkedOutObjVersion.ObjVer);`

However, this will not work if the user performing this operation has read-only access. Although the user can do it through M-Files client login.

As discussed in the [community](https://community.m-files.com/forums-1552881334/f/m-files-api/5168/how-to-move-to-a-workflow-state-when-user-has-read-only-permissions-through-rest-api/12827#12827), it is possible to do it through REST PUT operation, however its not exposed in the library yet.

It would be great if the library offers some method like : 
**ObjectOperations.MoveToState(ObjectVersion objVer, int stateId)**

**Comment by CraigHawker** [comment]
This was completed in PR #11 .

**Comment by shoebsd31** [comment]
Hi @CraigHawker , seems like the latest changes are not yet in the master. I guess the changes are lost while merging from approve-reject-assignment

**Comment by CraigHawker** [comment]
These appear to be in master: https://github.com/M-Files/Libraries.MFWSClient/blob/master/MFaaP.MFWSClient/MFWSVaultObjectPropertyOperations.cs#L1249

Can you confirm?

**Comment by shoebsd31** [comment]
strangely its not reflected in the nuget package

**Comment by CraigHawker** [comment]
Hi @shoebsd31

The changes were included in 1.2.1-alpha.  I can confirm that they are there by using the FuGet explorer website: https://www.fuget.org/packages/MFaaP.MFWSClient/1.2.1-alpha/lib/netstandard2.0/MFaaP.MFWSClient.dll/MFaaP.MFWSClient/MFWSVaultObjectPropertyOperations

Please make sure that you are targeting this alpha version.

Regards,

Craig.

**Comment by shoebsd31** [comment]
Hi @CraigHawker , 

sorry it was my nuget cache!. All good now :)
