### ISSUE TITLE
403 error when there are multiple vaults after authenticating via SSO.

### ISSUE THREAD

**Issue by lshen-ks** [M-Files/Libraries.MFWSClient#16]
Hi,

When using the cookie-based authentication (SSO), the active vaultId is not maintained in the http header. In the situation when there are multiple vaults, all following REST calls ended with 403 error.

Please add the X-Active-Vault header for cookie based auth. 

Thanks,
Lina

**Comment by CraigHawker** [comment]
Hi Lina,

Please can you test the fix in the issue-16 branch?  The nupkg can be downloaded here: https://github.com/M-Files/Libraries.MFWSClient/tree/issue-16/current.

You may need to add a local nuget folder source to allow you to test out the 1.2.4-alpha release on that branch.

If works then we can look at creating a pull request to get this into the main release.

Regards,

Craig.

**Comment by lshen-ks** [comment]
Thanks a lot, the issue is fixed in 1.2.4-alpha.
