### ISSUE TITLE
AuthenticateUsingSingleSignOn not working prior to M-Files 21.10

### ISSUE THREAD

**Issue by Ezeckiel2517** [M-Files/Libraries.MFWSClient#19]
I've try to used the client with SSO login but it seems to be formatting the vault guid in the url in lowercase, which result in Forbidden 403 error when trying to use the api.

Can this be changed to put the url in UPPERCASE for those who do not have the M-Files 2018 update 2110 yet which fix the guid case sensitive comparison.

Thanks

**Comment by Ezeckiel2517** [comment]
Also not sure why the guid is formatted using the format D while in AddVaultHeader it uses B.

**Comment by CraigHawker** [comment]
The first alteration (to work around the capitalisation of the guid before the fix) sounds like a good one. Please feel free to submit a pull request.

The second (around formatting) is also something that I'd consider a pull request for, although it would need testing against real-life implementations to ensure that the formatting works in various situations.

**Comment by Ezeckiel2517** [comment]
Pull Request #21

**Comment by CraigHawker** [comment]
Thank you for the PR; merged!  Marking the issue as closed, as this will be fixed in `1.3.0-alpha` which is being built/released right now.

**Comment by CraigHawker** [comment]
The version is being validated by nuget now: https://www.nuget.org/packages/MFaaP.MFWSClient/1.3.0-alpha
