### ISSUE TITLE
Issue with File Attachment in M-Files Vault using MFWSClient

### ISSUE THREAD

**Issue by chilu387** [M-Files/Libraries.MFWSClient#26]
Library Version: 2.0.2-issue-20
M-Files Admin Version:23.9.12966.6
M-Files Server Version: 23.6.12695.4

Context: 

Currently, I am working on implementing a file upload feature that allows users to select a file, define some property definitions, and upload it to the M-Files Vault. While the creation of a new document object is working smoothly (I followed the sample on GitHub on how to create a new object), I am encountering difficulties when it comes to appending the file to the object.
I came across the Client.ObjectFileOperations.AddFiles() function, but it returns a JSON error. 
 
“The JSON value could not be converted to System.Collections.Generic.List`1[MFaaP.MFWSClient.UploadInfo]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.”
[MFilesUploadExample.zip](https://github.com/M-Files/Libraries.MFWSClient/files/12856072/MFilesUploadExample.zip)

**Comment by CraigHawker** [comment]
The issue occurs because, if there's only one file in the collection, the REST API returns a different value.  I will look at this.

**Comment by CraigHawker** [comment]
Are you able to test this release, please?

https://www.nuget.org/packages/MFaaP.MFWSClient/2.0.0-issue-26

**Comment by chilu387** [comment]
Thank you! I received this issue: 

![image](https://github.com/M-Files/Libraries.MFWSClient/assets/91739984/2af306eb-6d4f-4c80-983f-1e6eac8af89b)

The CreateNewObject() function has returned a valid ID and files variable contains the correct file

**Comment by CraigHawker** [comment]
I will continue to look at this next week, I apologise that didn't help.

**Comment by chilu387** [comment]
No problem. Thank you very much for your help

**Comment by CraigHawker** [comment]
So that specific bit is an bug in your application.  At the moment you're passing a version of zero into the AddFiles method.  You should be passing null (or do not provide a value for the version; both indicate that you want to alter the latest version).

Changing that then - using the version of the library I published above - added the files to the object.

**Comment by chilu387** [comment]
Nice, it works now after changing the 0 to null. Thank you a lot!

**Comment by CraigHawker** [comment]
I will create a PR and look to get this merged.  Thanks for confirming!

**Comment by CraigHawker** [comment]
These changes are in https://www.nuget.org/packages/MFaaP.MFWSClient/23.10.0.15-prerelease (currently being validated by nuget).
