### ISSUE TITLE
AuthenticateUsingSingleSignOn no longer works after RestSharp changes

### ISSUE THREAD

**Issue by Ezeckiel2517** [M-Files/Libraries.MFWSClient#29]
Hi Craig, the method client.AuthenticateUsingSingleSignOn no longer works and throws an exception "Request failed with status code Unauthorized".

This is probably due to RestSharp changes to Credentials handling.

**Comment by CraigHawker** [comment]
I'll try to take a look at this. Are you able to link me to some details on these changes, plus confirm the version of restsharp you're referencing in your project so I can replicate it?

**Comment by Ezeckiel2517** [comment]
MFaaP.MFWSClient 23.10.0.15-prerelease
RestSharp 108.0.2 (minimum required)

Before I was using MFaaP.MFWSClient 1.2.3-alpha and RestSharp 106.12.
So it's not sure the problem is from v23 prerelease or from v2.x

**Comment by Ezeckiel2517** [comment]
Look likes after the RestSharp client is created, you can no longer changes the credentials. Modifying the client options has no effect because it is only used in the constructor.

The fix I can think of is to create a seperate client to handle the call.
I have created a PR for this.

**Comment by Ezeckiel2517** [comment]
[Documentation Reference](https://restsharp.dev/v107/#ntlm-authentication)

"it needs some settings to be provided for HttpClientHandler, which is set up before the HttpClient instance is created, and it happens once per RestClient instance, and it cannot be changed per request."

**Comment by CraigHawker** [comment]
Excellent, thank you.  I am actually out of the office for the next couple of days but will try to look at the PR early next week.

Seriously: thank you.  Not many people go to the effort of a PR, so it's very much appreciated.

**Comment by CraigHawker** [comment]
Version `24.1.0.16-prerelease` is currently being validated and contains this PR - thank you!
