### ISSUE TITLE
Constructor that accepts HttpClient is compiled out when using dotnet 6+

### ISSUE THREAD

**Issue by feinoujc** [M-Files/Libraries.MFWSClient#31]
[This constructor](https://github.com/M-Files/Libraries.MFWSClient/blob/c6e04af768853db963e364f90e17c942d9f87066/MFaaP.MFWSClient/MFWSClientBase.cs#L39-L50) does not appear to be available. The targets specified are [here ](https://github.com/M-Files/Libraries.MFWSClient/blob/c6e04af768853db963e364f90e17c942d9f87066/MFaaP.MFWSClient/MFaaP.MFWSClient.csproj#L4). When using the dotnet 6+ targets, this constructor is not available based on the use of this flag.

You could consider **just** targeting netstandard 2.0 because you are not using any newer apis (apparently)

https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0#when-to-target-net80-vs-netstandard

**Comment by CraigHawker** [comment]
I don't think that there was an explicit intention to alter the constructor behaviour between dotnet versions.  I would need to investigate more deeply as to why these preprocessor directives were added in the first place, though.  It looks like perhaps the RestSharp `RestClient` base class doesn't expose those constructors in certain environments, or perhaps didn't at some point in the past.

.NET Standard 2.0 should give us support for [almost everything](https://dotnet.microsoft.com/en-us/platform/dotnet-standard).  The notable exception is earlier .NET Framework runtimes (although this project doesn't multi-target for them either so should not change anything). Dotnet 8 is also not listed on that page, but I think that's a mistake as it's listed [here](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0).

So yes: I think that is probably a reasonable request, but those preprocessor directives concern me and need investigating.  If you are willing to create a PR then I would certainly look to merge it if we can.

**Comment by CraigHawker** [comment]
This has been merged - thank you!
The github action is running to build and publish it.  This change should be visible in version `24.1.0.17-prerelease` in nuget shortly.
