### ISSUE TITLE
[Feature Request] AssignmentsApproval in MFSW Client library 

### ISSUE THREAD

**Issue by shoebsd31** [M-Files/Libraries.MFWSClient#9]
Currently the following methods are available on Vault's ObjectPropertyOperations :

- ApproveOrRejectAssignment
- ApproveOrRejectAssignmentByUser

There's no such method available on MFWSClient.ObjectPropertyOperations

It would be great if these methods are also available on MFWSClient

**Comment by shoebsd31** [comment]
Hi Craig, I was trying to implement  **ApproveOrRejectAssignment** . I created a small workflow with approval assignment. 
I noticed the following properties getting set when an assignment is rejected or approved:

//////////in case of approval
Mark as completed by (Property def : 45) : <user id who performed the action>
Mark as rejected by (Property def : 97) : not set
Completed : (Property def : 98)  : true
 
//////////in case of rejection
Mark as completed by (Property def : 45): not set
Mark as rejected by (Property def : 97)  :  <user id who performed the action>
Completed : (Property def : 98) : true

so will the implementation be like : 

```
ApproveOrRejectAssignment(ObjVer objver, bool Approve)
{
//propertyValues would be set explicitly based on the bool. 
//should the USER ID be fetched from session info and set in the property values ?
var response = SetPropertiesAsync(objVer.Type, objVer.ID, propertyValues, false, objVer.Version, token);
            return response.Data;
}
```

Can you please give me the hints

**Comment by CraigHawker** [comment]
Hi @shoebsd31,

I took a quick look at this last week and I believe that it's possibly going to require the use of some undocumented endpoints.  For that reason I am going to remove the "help wanted" label, as I think this needs to be done by me.

I can't guarantee when I will be able to look at this, although my hope is that I will get some time this week.

Regards,

Craig.

**Comment by shoebsd31** [comment]
Hi Craig,

Thanks for letting me know if you could just add the undocumented endpoints,
I could help you with the implementation here.

Regards,
Shoeb

**Comment by shoebsd31** [comment]
For time being, I will just set up those properties on assignment class. I hope that's works for me now.

Regards,
Shoeb

**Comment by CraigHawker** [comment]
I have an initial implementation here: https://github.com/M-Files/Libraries.MFWSClient/tree/approve-or-reject-assignment

You will need to clone/download the branch and compile it as there's no compiled version available yet.

Regards,

Craig.

**Comment by shoebsd31** [comment]
Thanks Craig!
